version: '3.9'

services:
  springboot:
    build: .
    container_name: ParkingManagement
    ports:
      - "8083:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

      # ðŸ”‘ Neon connection (from Neon Console)
      SPRING_DATASOURCE_URL: jdbc:postgresql://ep-withered-night-afga8n1m-pooler.c-2.us-west-2.aws.neon.tech/parking?sslmode=require
      SPRING_DATASOURCE_USERNAME: neondb_owner
      SPRING_DATASOURCE_PASSWORD: npg_gR8tH7dfhZsz
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

    restart: always
